
@{
    ViewData["Title"] = "Index";
    Layout = "_Layout";
}

<div class="row">
    <div class="col">
        <div class="card" style="margin: 20px;">
            <div class="card-body">
                <h5 class="card-title">Capitulo 1: Controlando el flujo de un programa</h5>
                <h6 class="card-subtitle mb-2 text-muted">Tema 5: Implementar el manejo de exepciones</h6>
                <hr>
                <p class="card-text">
                    <h5>La construcción de try-catch</h5>
                    <ul>
                        <li>
                            El manejo de excepciones de construcción try-catch se realiza colocando el código que se protegerá en un bloque que sigue a la palabra clave try.
                            Este bloque de código puede ir seguido de un código de controlador de excepción, precedido por una palabra clave catch. El controlador de excepciones se
                            ejecuta en caso de que se produzca una excepción. El listado 1-76 muestra cómo funciona esto. Contiene un programa que lee una cadena de texto del usuario y
                            utiliza el método Parse de la clase int para convertir el texto en un entero. Este método generará una excepción si no puede convertir la cadena en un entero
                            válido.
                        </li>
                        <li>
                            El programa en el Listado 1-76 no usa el objeto de excepción que se produce cuando se lanza la excepción. El programa en el Listado 1-77 detecta la excepción
                            y usa las propiedades Message y StackTrace de la excepción para generar un mensaje de error.
                        </li>
                        <li>
                            A la palabra clave catch le sigue el tipo de excepción que se capturará y el nombre que se utilizará para referirse al objeto de excepción durante el
                            controlador de excepciones. En el Listado 1-77, el valor de ex se establece para hacer referencia a la excepción que genera el método Parse si falla. Si el
                            usuario ingresa un número no válido, la salida del programa aparecerá como se muestra a continuación. La primera línea de la salida muestra el mensaje de
                            error y StackTrace proporciona la posición en el programa en el que ocurrió el error. La propiedad HelpLink se puede configurar para proporcionar más
                            información sobre la excepción. La propiedad TargetSite proporciona el nombre del método que causa la excepción, y la propiedad Source proporciona el nombre
                            de la aplicación que causó el error, o el nombre del ensamblado si el nombre de la aplicación no se ha establecido. La salida aquí muestra el resultado de la
                            excepción.
                        </li>
                        <li>
                            Ingrese un número entero: fred Mensaje: la cadena de entrada no tenía el formato correcto.
                        </li>
                    </ul>
                </p>
            </div>
        </div>
    </div>
</div>